steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh vm-created-by-deployment-manager --zone=us-central1-f --command='/bin/sh /home/mmc/pull.sh'