steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh vm-compute-app --zone=us-centeral1-f --command='/bin/sh /home/mmc/pull.sh'

# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   id: Update staging server
#   # waitFor: ['-']
#   entrypoint: /bin/sh
#   args: ['gcloud','compute','ssh','vm-created-by-deployment-manager','--zone','us-centeral1-f','--command','/bin/sh /home/mmc/pull.sh']
    # - '-c'
    # - >
    #   gcloud compute ssh vm-created-by-deployment-manager --zone=us-central1-f --command='/bin/sh /home/mmc/pull.sh'